Project_NAT/urls.py
from django.contrib import admin
from django.urls import path, include
# import login function
from django.contrib.auth import views as auth_views
# import fuction upload photo
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('app_product.urls', 'app_product'), namespace = 'app_product')),
    path('', include(('app_general.urls', 'app_general'), namespace = 'app_general')),
    # Mapping login and logout
    path('login/', auth_views.LoginView.as_view(template_name='app_general/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='app_general/logout.html'), name='logout'),
]

# Path upload photo
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_general/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.Home, name='home-page'),
    path('about_user/', views.AboutUser, name='about_user-page'),
    path('register_user/', views.RegisterUser, name='register_user-page'),
    path('contact/',views.ContactMessage, name='contact-page'),
    re_path(r'^add_to_cart/(?P<slug>[\w-]+)/$', views.add_to_cart, name='add_to_cart-page'),
    path('cart/', views.cart_list, name='cart_list-page'),
	re_path(r'^delete_cart/(?P<slug>[\w-]+)/$', views.cart_delete, name='delete_product-page'),
	path('order/', views.order, name='order-page'),
    path('add_customers/', views.Add_Customer, name='add-customer-page'),
    path('order/del_customers/<customer_id>', views.Delete_Customer, name='del_customer-page'),
	path('order/<customer_id>/', views.Select_Customer, name='select_customer-page'),
    path('thank_you/', views.Thankyou, name='thank_you-page'),
    path('history_shopping/', views.history_shopping, name='history_shop-page')
]

app_product/urls.py
from django.urls import path
from app_product import views

urlpatterns = [
	path('', views.All_Products, name='products-page' ),
	path('<product_code>', views.One_Product, name='product-page'),
	path('coffee/', views.All_Coffee, name='products_coffee-page'),
	path('tea/', views.All_Tea, name='products_tea-page'),
	path('milk/', views.All_Milk, name='products_milk-page'),
	path('cake/', views.All_Cake, name='products_cake-page'),
]

app_general/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Contact(models.Model):
    contact_id = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    title = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    description = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{} : {}'.format(self.title, self.email)

class Customer(models.Model):
    customer_id = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    first_name = models.CharField(max_length = 225)
    last_name = models.CharField(max_length = 225)
    country = models.CharField(max_length = 225)
    city = models.CharField(max_length = 225)
    address = models.CharField(max_length = 225)
    phone = models.CharField(max_length = 225)
    def __str__(self) -> str:
    	return f'{self.first_name} {self.last_name}'

class Delivery(models.Model):
    STATUS = [
        ('Disapproved', 'Disapproved'), 
        ('Approve', 'Approve'), 
        ('Banned', 'Banned')
    ]
    PAYMENT = [
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Bank Transfer', 'Bank Transfer')
    ]
    delivery_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey('app_general.Customer', on_delete = models.CASCADE, null = True)
    status = models.CharField(max_length = 50, choices = STATUS, default = 'Disapproved')
    note = models.CharField(max_length = 100, null = True)
    payment_method = models.CharField(max_length = 50, choices = PAYMENT, default = 'Cash On Delivery')
    delivery_date = models.DateTimeField(auto_now_add = True)

class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    delivery = models.ForeignKey('app_general.Delivery', on_delete = models.CASCADE, null = True)
    product = models.ForeignKey('app_product.Product',  on_delete = models.CASCADE, null = True)
    quantity = models.IntegerField()
    unit_price = models.IntegerField()
    total_price = models.IntegerField()
    order_date = models.DateTimeField(auto_now_add = True)

app_general/forms.py
from django import forms
from app_product.models import *
from app_general.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ContactForm(forms.ModelForm):
	title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	description = forms.CharField(max_length=255, widget=forms.Textarea(attrs={'class':'form-control'}))
	class Meta:
		model = Contact
		fields = ('title','email','description')

class RegisterUserForm(UserCreationForm):
	first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	class Meta:
		model = User
		fields = ('username','first_name','last_name','email','password1','password2')
	def __init__(self, *args, **kwargs):
		super(RegisterUserForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['class'] = 'form-control'

class CustomerForm(forms.ModelForm):
	# Adjust from delivery
	first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(label='Last Name', widget=forms.TextInput(attrs={'class':'form-control'}))
	country = forms.CharField(label="Country", widget=forms.TextInput(attrs={'class':'form-control'}))
	city = forms.CharField(label="City", widget=forms.TextInput(attrs={'class':'form-control'}))
	address = forms.CharField(label="Address", widget=forms.TextInput(attrs={'class':'form-control'}))
	phone = forms.CharField(label="Phone Number", widget=forms.TextInput(attrs={'class':'form-control'}))
	class Meta:
		model = Customer
		fields = ('first_name','last_name','country','city','address','phone')

class OrderForm(forms.ModelForm):
	PAYMENT = [
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Bank Transfer', 'Bank Transfer')
	]
	payment_method = forms.ChoiceField(label="Payment Method", required = True, choices = PAYMENT, widget=forms.RadioSelect)	
	note = forms.CharField(label="Message", initial="No Comment", widget=forms.TextInput(attrs={'class':'form-control'}))
	class Meta:
		model = Delivery
		fields = ('payment_method','note')

app_general/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from app_general.forms import *
from django.contrib.auth import authenticate, login
from django.contrib import messages
from app_product.models import Product
from django.contrib.auth.models import User

# Create your views here.

# Home-Page
def Home(request):
	return render(request, 'app_general/home.html')

# AboutMe-Page (login requirement)
@login_required
def AboutUser(request):
	return render(request, 'app_general/about.html')

# Register-Page (After register auto login)
def RegisterUser(request):
	if request.method == "POST":
		form = RegisterUserForm(request.POST)
		if form.is_valid():
			form.save()
			data_username = form.cleaned_data['username']
			data_password = form.cleaned_data['password1']
			user = authenticate(username=data_username, password=data_password)
			login(request, user)
			messages.success(request, ("Registration Successful"))
			return redirect('app_general:home-page')
	else:
		form = RegisterUserForm()
	context = { 'form' : form }
	return render(request, 'app_general/register.html', context)

# Contact-Page
def ContactMessage(request):
	if request.method == "POST":
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('app_general:home-page')
	else:
		form = ContactForm()
	context = { 'form' : form }
	return render(request, 'app_general/contact.html', context)

# Add Product Function in Cart
# Note Variable
# Price 1. price >> normal price | 2. special_price >> special price  | 3. product_price >> real price | 4. total_price >> summation price of product in cart
# Quantities 1. quantity >> quantity of product in database | 2. qty >> quantities of product in cart
@login_required
def add_to_cart(request, slug):
	product = get_object_or_404(Product, slug = slug)
	cart_items = request.session.get('cart_items') or []
	item_in_cart = False
	if product.quantity >= 1:
		# Update item in cart ( Have this item in cart )
		for item in cart_items:
			if item.get('slug') == product.slug:
				# Update product price
				if item.get('special_price') is not None:
					item['product_price'] = int(item.get('special_price'))
				# Update product quantities
				if product.quantity > item['qty']:
					item['qty'] = int(item.get('qty')) + 1
					item['total_price'] = int(item.get('qty')) * int(item.get('product_price'))
				item_in_cart = True
		# Add new item in cart
		if not item_in_cart:
			# Update product price
			if product.special_price is not None:
				product_price = product.special_price
			else:
				product_price = product.price
			cart_items.append({
				'product_id' : product.product_id,
				'product_code' : product.product_code,
				'slug' : product.slug,
				'title' : product.title,
				'price' : product.price,
				'product_price' : product_price,
				'qty' : 1,
				'total_price' : product_price,
			})
		request.session['cart_items'] = cart_items
	# Connect to cart_list function
	return HttpResponseRedirect(reverse('app_general:cart_list-page'))

# Delete Product Function in Cart
def cart_delete(request, slug):
	cart_items = request.session.get('cart_items') or []
	for i in range(len(cart_items)):
		if cart_items[i]['slug'] == slug:
			del cart_items[i]
			break
	request.session['cart_items'] = cart_items
	# Connect to cart_list function
	return HttpResponseRedirect(reverse('app_general:cart_list-page', kwargs={}))

# Cart-Page
@login_required
def cart_list(request):
	cart_items = request.session.get('cart_items') or []
	total_qty = 0
	total_price = 0
	add_shipping_cost = False
	# Update total quantity and total price of product
	for item in cart_items:
		total_price += item.get('total_price')
		total_qty += item.get('qty')
	request.session['total_qty'] = total_qty
	request.session['total_price'] = total_price
	request.session['add_shipping_cost'] = add_shipping_cost
	if request.method == "POST":
		# Connect to order function
		return HttpResponseRedirect(reverse('app_general:order-page', kwargs={}))
	return render(request, 'app_general/cart.html', {'cart_items' : cart_items,})

# Register Customer Function and save to Database
@login_required
def Add_Customer(request):
	customer = []
	if request.method == "POST":
		form = CustomerForm(request.POST)
		if form.is_valid():
			customer.append({
				'first_name' : form.cleaned_data['first_name'],
				'last_name' : form.cleaned_data['last_name'],
				'country' : form.cleaned_data['country'],
				'city' : form.cleaned_data['city'],
				'address' : form.cleaned_data['address'],
				'phone' : form.cleaned_data['phone']
			})
		# Add new customer to database
		username = request.user.username
		new_customer = Customer()
		new_customer.user = User.objects.get(username=username)
		new_customer.first_name = customer[0]['first_name']
		new_customer.last_name = customer[0]['last_name']
		new_customer.country = customer[0]['country']
		new_customer.city = customer[0]['city']
		new_customer.address = customer[0]['address']
		new_customer.phone = customer[0]['phone']
		new_customer.save()
		request.session['customer'] = customer
		request.session['customer_id'] = new_customer.customer_id
		# Connect to order function
		return HttpResponseRedirect(reverse('app_general:order-page'))
	else:
		form = CustomerForm()
	return render(request, 'app_general/add_customer.html', {
		'form':form,
		})

# Select Customer Function in Database
def Select_Customer(request, customer_id):
	customers = Customer.objects.get(customer_id = customer_id)
	customer = []
	customer.append({
		'first_name' : customers.first_name,
		'last_name' : customers.last_name,
		'country' : customers.country,
		'city' : customers.city,
		'address' : customers.address,
		'phone' : customers.phone
	})
	request.session['customer'] = customer
	request.session['customer_id'] = customers.customer_id
	# Connect to order function
	return HttpResponseRedirect(reverse('app_general:order-page', kwargs={}))

# Delete customer Function in Database
def Delete_Customer(request, customer_id):
	del_customer = Customer.objects.get(customer_id = customer_id)
	del_customer.delete()
	request.session['customer'] = []
	# Connect to order function
	return HttpResponseRedirect(reverse('app_general:order-page', kwargs={}))

# order Function
@login_required
def order(request):
	cart_items = request.session.get('cart_items') or []
	customer = request.session.get('customer') or []
	customer_id = request.session.get('customer_id') or []
	total_price = request.session.get('total_price') or []
	add_shipping_cost = request.session.get('add_shipping_cost')
	all_customer = Customer.objects.all()
	shipping_cost = 40
	try:
		my_order = True
		# update total price (+ shipping cost)
		if not add_shipping_cost:
			total_price += shipping_cost
			add_shipping_cost = True
			request.session['total_price'] = total_price
			request.session['add_shipping_cost'] = add_shipping_cost
		if request.method == "POST":
			# Part delivery (+ data for note and payment_method)
			delivery = []
			form = OrderForm(request.POST)
			if form.is_valid():
				delivery.append({
					'note' : form.cleaned_data['note'],
					'payment_method' : form.cleaned_data['payment_method']
				})
				request.session['delivery'] = delivery
			# Save Delivery to database
			new_delivery = Delivery()
			try:
				new_delivery.customer = Customer.objects.get(customer_id = customer_id)
				new_delivery.note = delivery[0]['note']
				new_delivery.payment_method = delivery[0]['payment_method']
				new_delivery.save()
			except:
				return HttpResponseRedirect(reverse('app_general:order-page'))
			# Save new order in database
			for data in range(len(cart_items)):
				new_order = Order()
				new_order.delivery = Delivery.objects.all().last()
				new_order.product = Product.objects.get(product_id = cart_items[data]['product_id'])
				new_order.quantity = cart_items[data]['qty']
				new_order.unit_price = cart_items[data]['product_price']
				new_order.total_price = cart_items[data]['total_price']
				new_order.save()
				# Update quantity of product in database
				update_quantity = get_object_or_404(Product, product_code = cart_items[data]['product_code'])
				update_quantity.quantity -= new_order.quantity
				update_quantity.save()
			request.session['total_qty']  = []
			request.session['cart_items']  = []
			request.session['total_price'] = []
			# Connect to Thankyou function
			return HttpResponseRedirect(reverse('app_general:thank_you-page'))
		else:
			form = OrderForm()
	except:
		my_order = False
		form = OrderForm()
	context = {
		'form' : form,
		'all_customer' : all_customer,
		'cart_items' : cart_items,
		'customer' : customer,
		'shipping_cost' : shipping_cost,
		'my_order' : my_order
	}
	return render(request, 'app_general/order.html', context)

# ThankYou-Page (After Checkout in Order-Page)
@login_required
def Thankyou(request):
	return render(request, 'app_general/thank_for_shopping.html')

# History Shopping
@login_required
def history_shopping(request):
	account = request.user.username
	username = User.objects.get(username=account)
	customers = Customer.objects.filter(user=username)
	history_shop = []
	# Filter data
	for customer in customers:
		deliveries = Delivery.objects.filter(customer_id = customer)
		for delivery in deliveries:
			orders = Order.objects.filter(delivery = delivery.delivery_id)
			for order in orders:
				products = Product.objects.filter(product_id = order.product_id)
				for product in products:
					history_shop.append({
						'delivery' : delivery.delivery_id,
						'date' : delivery.delivery_date.strftime('%Y/%m/%d'),
						'customer' : customer,
						'product' : product.title,
						'quantities' : order.quantity,
						'total_price' : order.total_price
					})
	status = len(history_shop)
	context = {
		'history_shop' : history_shop,
		'status' : status
	}

app_general/templates/app_general/component/site_footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'app_general:home-page' %}" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Company, Inc</p>
    <p class="text-center text-muted">Note : This project web application is made for programming education purposes only.</p>
</footer>

app_general/templates/app_general/component/site_header.html
<header class="mb-auto sticky-top">
    <div class="navbar navbar-dark shadow-sm p-md-2 mb-2 bg-black">
        <div class="container text-white flex-md-row bg-black">
            <div class="flex-md-col-3 bg-black">
                <a href="{% url 'app_general:about_user-page' %}" class="navbar-brand d-flex align-items-center">
                    <strong>{{ user.username }}</strong>
                </a>
            </div>
            <!-- Menu bar -->
            <div class="row bg-black">
                <div class="dropdown col">
                    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownProduct"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Product
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownProduct">
                        <li><a class="dropdown-item" href="{% url 'app_product:products-page' %}">My Product</a></li>
                        <li><a class="dropdown-item" href="{% url 'app_product:products_coffee-page' %}">Coffee</a></li>
                        <li><a class="dropdown-item" href="{% url 'app_product:products_tea-page' %}">Tea</a></li>
                        <li><a class="dropdown-item" href="{% url 'app_product:products_milk-page' %}">Milk</a></li>
                        <li><a class="dropdown-item" href="{% url 'app_product:products_cake-page' %}">Cake</a></li>
                    </ul>
                </div>
                <!-- Show quantities of product in cart -->
                <div class="col">
                    <a class="btn btn-dark position-relative" href="{% url 'app_general:cart_list-page' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                            <path
                                d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0z" />
                        </svg>
                        {% if request.session.total_qty %}
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{ request.session.total_qty }}
                        </span>
                        {% endif %}
                    </a>
                </div>
                <div class="col">
                    <a class="btn btn-dark col" href="{% url 'app_general:contact-page' %}">
                        Contact
                    </a>
                </div>
            </div>
            <!-- Button of toggler -->
            <div class="flex-md-col-3 bg-black">
                <a class="nav-link fw-bold py-1 px-0 text-primary" type="button" align="left">
                    <div data-bs-toggle="offcanvas" data-bs-target="#demo">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false"
                            aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- Pop-up menu from button of toggler -->
    <div class="offcanvas offcanvas-bottom h-auto bg-dark cover-container mx-auto" id="demo">
        <div class="offcanvas-body">
            <div class="text-white">
                <h4><b>{{ user.username }}</b></h4>
            </div>
            <a class="nav-link fw-bold py-1 px-0 text-white" href="{% url 'app_general:home-page' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-house-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                        d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
                    <path fill-rule="evenodd"
                        d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z" />
                </svg>&nbsp Home
            </a>
            <a class="nav-link fw-bold py-1 px-0 text-white" href="{% url 'app_general:about_user-page' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-person-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                </svg>&nbsp My Account
            </a>
            <a class="nav-link fw-bold py-1 px-0 text-white" href="{% url 'app_general:contact-page' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path
                        d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z" />
                </svg>&nbsp Contact
            </a>
            <br>
            <a class="btn btn-danger text-white text-white" type="button" href="{% url 'logout' %}"><b>Sign out</b></a>
        </div>
    </div>
</header>