Project_NAT/urls.py
from django.contrib import admin
from django.urls import path, include
# import login function
from django.contrib.auth import views as auth_views
# import fuction upload photo
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('app_product.urls', 'app_product'), namespace = 'app_product')),
    path('', include(('app_general.urls', 'app_general'), namespace = 'app_general')),
    # Mapping login and logout
    path('login/', auth_views.LoginView.as_view(template_name='app_general/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='app_general/logout.html'), name='logout'),
]

# Path upload photo
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_general/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.Home, name='home-page'),
    path('about_user/', views.AboutUser, name='about_user-page'),
    path('register_user/', views.RegisterUser, name='register_user-page'),
    path('contact/',views.ContactMessage, name='contact-page'),
    re_path(r'^add_to_cart/(?P<slug>[\w-]+)/$', views.add_to_cart, name='add_to_cart-page'),
    path('cart/', views.cart_list, name='cart_list-page'),
	re_path(r'^delete_cart/(?P<slug>[\w-]+)/$', views.cart_delete, name='delete_product-page'),
	path('order/', views.order, name='order-page'),
    path('add_customers/', views.Add_Customer, name='add-customer-page'),
    path('order/del_customers/<customer_id>', views.Delete_Customer, name='del_customer-page'),
	path('order/<customer_id>/', views.Select_Customer, name='select_customer-page'),
    path('thank_you/', views.Thankyou, name='thank_you-page'),
    path('history_shopping/', views.history_shopping, name='history_shop-page')
]

app_product/urls.py
from django.urls import path
from app_product import views

urlpatterns = [
	path('', views.All_Products, name='products-page' ),
	path('<product_code>', views.One_Product, name='product-page'),
	path('coffee/', views.All_Coffee, name='products_coffee-page'),
	path('tea/', views.All_Tea, name='products_tea-page'),
	path('milk/', views.All_Milk, name='products_milk-page'),
	path('cake/', views.All_Cake, name='products_cake-page'),
]

app_product/models.py
from django.db import models

# Create your models here.

class Product_Type(models.Model):
	# Rename of Product_Type in admin site
	class Meta:
		verbose_name_plural = 'Type'
	# Determine Variable in Database
	category = models.ForeignKey('app_product.Product_Category', on_delete = models.CASCADE, null = True)
	type_id = models.AutoField(primary_key = True)
	title = models.CharField(max_length = 50)
	# Show Product_Type in title form
	def __str__(self) -> str:
		return f'{self.title}'

class Product_Category(models.Model):
	class Meta:
		verbose_name_plural = 'Category'
	category_id = models.AutoField(primary_key = True)
	title = models.CharField(max_length = 50)
	def __str__(self) -> str:
		return f'{self.title}'

class Product(models.Model):
	class Meta:
		verbose_name_plural = 'All Product'
	product_id = models.AutoField(primary_key = True)
	product_code = models.CharField(unique = True, max_length = 50)
	type = models.ForeignKey('app_product.Product_Type', on_delete = models.CASCADE, null = True)
	title = models.CharField(max_length = 225)
	description = models.TextField(blank = True, null = True)
	slug = models.SlugField(unique = True, max_length = 100)
	price = models.IntegerField(blank = True, null = True)
	special_price = models.IntegerField(blank = True, null = True)
	quantity = models.IntegerField(blank = True, null = True)
	is_premium = models.BooleanField(default = False)
	promotion_end = models.DateTimeField(blank = True, null = True)
	photo = models.ImageField(default = 'default.png', upload_to="image_product", blank=True, null=True)
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True, blank = True, null = True)	
	def __str__(self) -> str:
		return f'{self.title}'

app_product/forms.py
from django import forms

app_product/views.py
from django.shortcuts import render
from app_product.models import Product
from app_product.forms import *

# Create your views here.
# Note 
# type >> 1 = coffee, 2 = tea, 3 = milk, 4 = cake

def All_Products(request):
	all_products = Product.objects.all()
	check_product = len(all_products)
	context = { 
		'products' : all_products,
		'check_product' : check_product
	}
	return render(request, 'app_product/products.html', context)

def One_Product(request, product_code):
	one_product = None
	try:
		one_product = Product.objects.get(product_code = product_code)
	except:
		print('Not Found!')
	context = {'product' : one_product}
	return render(request, 'app_product/product.html', context)

def All_Coffee(request):
	all_coffee = Product.objects.filter(type = 1)
	check_product = len(all_coffee)
	context = { 
		'coffee' : all_coffee,
		'check_product' : check_product
	}
	return render(request, 'app_product/coffee.html', context)

def All_Tea(request):
	all_tea = Product.objects.filter(type = 2)
	check_product = len(all_tea)
	context = { 
		'tea' : all_tea,
		'check_product' : check_product
	}
	return render(request, 'app_product/tea.html', context)

def All_Milk(request):
	all_milk = Product.objects.filter(type = 3)
	check_product = len(all_milk)
	context = { 
		'milk' : all_milk,
		'check_product' : check_product
	}
	return render(request, 'app_product/milk.html', context)

def All_Cake(request):
	all_cake = Product.objects.filter(type = 4)
	check_product = len(all_cake)
	context = { 
		'cake' : all_cake,
		'check_product' : check_product
	}
	return render(request, 'app_product/cake.html', context)

app_product/templates/app_product/cake.html
{% extends 'app_general/base.html' %}

{% load static %}

{% block title %}
<title>Products | Cake</title>
{% endblock %}

{% block content %}
<div class="container text-white" align="center">
    <h1>Cake</h1>
</div>
{% if check_product == 0 %}
<div class="container mt-3 text-muted text-center">
    <h3>Don't have product.</h3>
</div>
{% else %}
<div class="container mt-3 row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    {% for product in cake %}
    <!-- Product detail -->
    <div class="col">
        <div class="card shadow-sm mb-1">
            {% if product.photo %}
            <img class="card-img-top" src="{{ product.photo.url }}" alt="Card image" style="width:100%">
            {% endif %}
            <small class="text-muted text-end p-1">{{ product.product_code }}</small>
            <div class="card-body">
                <a class="card-title fw-bold text-white btn btn-success position-relative"
                    href="{% url 'app_product:product-page' product.product_code %}">
                    {{ product.title }}
                    {% if product.is_premium %}
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-black">
                        Premium !
                    </span>
                    {% endif %}
                </a>
                <p class="card-text">
                    <b> :: {{ product.type }} :: </b><br>
                    <!-- Check quantity of product -->
                    {% if product.quantity is not None %}
                    <b>Quantity : </b>{{ product.quantity }}<br>
                    {% else %}
                    <b class="text-danger">There are no order yet!</b><br>
                    {% endif %}
                    <!-- Update price of product -->
                    {% if product.special_price is not None %}
                    <b>Price : </b><del style="color:rgb(255, 90, 90)">{{ product.price | floatformat:'g' }}
                        Bath</del>&nbsp&nbsp{{ product.special_price | floatformat:'g' }} Bath<br>
                    {% else %}
                    {% if product.price is not None %}
                    <b>Price : </b>{{ product.price | floatformat:'g' }} Bath<br>
                    {% else %}
                    <br>
                    {% endif %}
                    {% endif %}
                    <!-- Check promotion end of product -->
                    {% if product.promotion_end is not None %}
                    <b>Promotion End : </b>{{ product.promotion_end | date:'j N Y' }}<br>
                    {% else %}
                    <br>
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <!-- Update status of product -->
                        {% if product.quantity == 0 %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Sold out</button>
                        {% else %}
                        {% if product.quantity is not None %}
                        <a type="button" class="btn btn-sm btn-primary fw-bold"
                            href="{% url 'app_general:add_to_cart-page' slug=product.slug %}">Add to Cart</a>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Empty</button>
                        {% endif %}
                        {% endif %}
                        <a class="btn btn-sm btn-link"
                            href="{% url 'app_product:product-page' product.product_code %}">Learn more</a>
                    </div>
                    <!-- Update date for edit -->
                    <small class="text-muted">{{ product.updated | date:'j N Y' }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

app_product/templates/app_product/coffee.html
{% extends 'app_general/base.html' %}

{% load static %}

{% block title %}
<title>Products | Coffee</title>
{% endblock %}

{% block content %}
<div class="container text-white" align="center">
    <h1>Coffee</h1>
</div>
{% if check_product == 0 %}
<div class="container mt-3 text-muted text-center">
    <h3>Don't have product.</h3>
</div>
{% else %}
<div class="container mt-3 row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    {% for product in coffee %}
    <!-- Product detail -->
    <div class="col">
        <div class="card shadow-sm mb-1">
            {% if product.photo %}
            <img class="card-img-top" src="{{ product.photo.url }}" alt="Card image" style="width:100%">
            {% endif %}
            <small class="text-muted text-end p-1">{{ product.product_code }}</small>
            <div class="card-body">
                <a class="card-title fw-bold text-white btn btn-success position-relative"
                    href="{% url 'app_product:product-page' product.product_code %}">
                    {{ product.title }}
                    {% if product.is_premium %}
                    <span
                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-black">
                        Premium!
                    </span>
                    {% endif %}
                </a>
                <p class="card-text">
                    <b> :: {{ product.type }} :: </b><br>
                    <!-- Check quantity of product -->
                    {% if product.quantity is not None %}
                    <b>Quantity : </b>{{ product.quantity }}<br>
                    {% else %}
                    <b class="text-danger">There are no order yet!</b><br>
                    {% endif %}
                    <!-- Update price of porduct -->
                    {% if product.special_price is not None %}
                    <b>Price : </b><del style="color:rgb(255, 90, 90)">{{ product.price | floatformat:'g' }}
                        Bath</del>{{ product.special_price | floatformat:'g' }} Bath<br>
                    {% else %}
                    {% if product.price is not None %}
                    <b>Price : </b>{{ product.price | floatformat:'g' }} Bath<br>
                    {% else %}
                    <br>
                    {% endif %}
                    {% endif %}
                    <!-- Check promotion end of product -->
                    {% if product.promotion_end is not None %}
                    <b>Promotion End : </b>{{ product.promotion_end | date:'j N Y' }}<br>
                    {% else %}
                    <br>
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <!-- Update status of product -->
                        {% if product.quantity == 0 %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Sold out</button>
                        {% else %}
                        {% if product.quantity is not None %}
                        <a type="button" class="btn btn-sm btn-primary fw-bold"
                            href="{% url 'app_general:add_to_cart-page' slug=product.slug %}">Add to Cart</a>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Empty</button>
                        {% endif %}
                        {% endif %}
                        <a class="btn btn-sm btn-link" href="{% url 'app_product:product-page' product.product_code %}">
                            Learn more
                        </a>
                    </div>
                    <!-- Update date for edit -->
                    <small class="text-muted">{{ product.updated | date:'j N Y' }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

app_product/templates/app_product/milk.html
{% extends 'app_general/base.html' %}

{% load static %}

{% block title %}
<title>Products | Milk</title>
{% endblock %}

{% block content %}
<div class="container text-white" align="center">
    <h1>Milk</h1>
</div>
{% if check_product == 0 %}
<div class="container mt-3 text-muted text-center">
    <h3>Sorry we don't have product.</h3>
</div>
{% else %}
<div class="container mt-3 row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    {% for product in milk %}
    <!-- Product detail -->
    <div class="col">
        <div class="card shadow-sm mb-1">
            {% if product.photo %}
            <img class="card-img-top" src="{{ product.photo.url }}" alt="Card image" style="width:100%">
            {% endif %}
            <small class="text-muted text-end p-1">{{ product.product_code }}</small>
            <div class="card-body">
                <a class="card-title fw-bold text-white btn btn-success position-relative"
                    href="{% url 'app_product:product-page' product.product_code %}">
                    {{ product.title }}
                    {% if product.is_premium %}
                    <span
                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-black">
                        Premium!
                    </span>
                    {% endif %}
                </a>
                <p class="card-text">
                    <b> :: {{ product.type }} :: </b><br>
                    <!-- Check quantity of product -->
                    {% if product.quantity is not None %}
                    <b>Quantity : </b>{{ product.quantity }}<br>
                    {% else %}
                    <b class="text-danger">There are no order yet!</b><br>
                    {% endif %}
                    <!-- Update price of product -->
                    {% if product.special_price is not None %}
                    <b>Price : </b><del style="color:rgb(255, 90, 90)">{{ product.price | floatformat:'g' }}
                        Bath</del>{{ product.special_price | floatformat:'g' }} Bath<br>
                    {% else %}
                    {% if product.price is not None %}
                    <b>Price : </b>{{ product.price | floatformat:'g' }} Bath<br>
                    {% else %}
                    <br>
                    {% endif %}
                    {% endif %}
                    <!-- Check promotion end of product -->
                    {% if product.promotion_end is not None %}
                    <b>Promotion End : </b>{{ product.promotion_end | date:'j N Y' }}<br>
                    {% else %}
                    <br>
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <!-- Update status of product -->
                        {% if product.quantity == 0 %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Sold out</button>
                        {% else %}
                        {% if product.quantity is not None %}
                        <a type="button" class="btn btn-sm btn-primary fw-bold"
                            href="{% url 'app_general:add_to_cart-page' slug=product.slug %}">Add to Cart</a>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Empty</button>
                        {% endif %}
                        {% endif %}
                        <a class="btn btn-sm btn-link" href="{% url 'app_product:product-page' product.product_code %}">
                            Learn more
                        </a>
                    </div>
                    <!-- Update date for edit -->
                    <small class="text-muted">{{ product.updated | date:'j N Y' }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

app_product/templates/app_product/product.html
{% extends 'app_general/base.html' %}

{% load static %}

{% block title %}
<title>Product | {{product.title}}</title>
{% endblock %}

{% block content %}
{% if product is not None %}
<div class="row bg-black" align="center">
    <div class="col-2">
        <a class="btn btn-black" href="{% url 'app_product:products-page' %}">
            <svg style="color:rgb(130, 130, 130)" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
        </a>
    </div>
</div>
<div class="container text-white">
    <br>
    <p>
        {% if product.photo %}
        <img class="card-img-top" src="{{ product.photo.url }}" alt="Card image" style="width:50%">
        {% endif %}
    <div>
        <a class="card-title fw-bolder text-white btn btn-success position-relative">
            {{ product.title }} <small class="text-black text-end p-1">{{ product.product_code }}</small>
            <!-- Check premium of product -->
            {% if product.is_premium %}
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-black">
                Premium!
            </span>
            {% endif %}
        </a>
        <!-- Check type of product -->
        <div class="text-muted">
            <h6>Product Type : {{ product.type }}</h6>
        </div>
    </div>
    </p>
    <p>
        <!-- Check quantity of product -->
        {% if product.quantity is not None %}
        <b>Quantity : </b>{{ product.quantity }}
        {% else %}
        <h6 class="text-danger">There are no order yet!</h6>
        {% endif %}
    </p>
    <p>
        <!-- Update price of product -->
        {% if product.special_price is not None %}
        <b>Price : </b><del style="color:rgb(255, 90, 90)">{{ product.price | floatformat:'g' }} Bath</del>&nbsp{{ product.special_price | floatformat:'g' }} Bath
        {% else %}
        {% if product.price is not None %}
        <b>Price : </b>{{ product.price | floatformat:'g' }} Bath
        {% endif %}
        {% endif %}
    </p>
    <p>
        <!-- Check promotion of product -->
        {% if product.promotion_end is not None %}
        <b>Promotion End : </b>{{ product.promotion_end | date:'j N Y' }}
        {% endif %}
    </p>
    <p>
        <!-- Show description -->
        <b>Description : </b><br>
        &nbsp;&nbsp;&nbsp;&nbsp; {{ product.description }}
    </p>
    <p>
        <!-- Update status of product -->
        {% if product.quantity == 0 %}
        <button type="button" class="card-title fw-bolder text-white btn btn-danger position-relative">Sold out</button>
        {% else %}
        {% if product.quantity is not None %}
        <a type="button" class="card-title fw-bolder text-white btn btn-primary position-relative"
            href="{% url 'app_general:add_to_cart-page' slug=product.slug %}">Add to Cart</a>
        {% else %}
        <button type="button" class="btn btn-danger fw-bold">Empty</button>
        {% endif %}
        {% endif %}
    </p>
</div>
{% else %}
<h3>Sorry we don't have product</h3>
{% endif %}
{% endblock %}

app_product/templates/app_product/products.html
{% extends 'app_general/base.html' %}

{% load static %}

{% block title %}
<title>Products | All Planets</title>
{% endblock %}

{% block content %}
<div class="container text-white" align="center">
    <h1>Products</h1>
</div>
{% if check_product == 0 %}
<div class="container mt-3 text-muted text-center">
    <h3>Don't have product.</h3>
</div>
{% else %}
<div class="container mt-3 row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    {% for product in products %}
    <!-- Product detail -->
    <div class="col">
        <div class="card shadow-sm mb-1">
            {% if product.photo %}
            <img class="card-img-top" src="{{ product.photo.url }}" alt="Card image" style="width:100%">
            {% endif %}
            <small class="text-muted text-end p-1">{{ product.product_code }}</small>
            <div class="card-body">
                <a class="card-title fw-bold text-white btn btn-success position-relative"
                    href="{% url 'app_product:product-page' product.product_code %}">
                    {{ product.title }}
                    {% if product.is_premium %}
                    <span
                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-black">
                        Premium !
                    </span>
                    {% endif %}
                </a>
                <p class="card-text">
                    <b> :: {{ product.type }} :: </b><br>
                    {% if product.quantity is not None %}
                    <!-- Check quantity of product -->
                    <b>Quantity : </b>{{ product.quantity }}<br>
                    {% else %}
                    <b class="text-danger">There are no order yet!</b><br>
                    {% endif %}
                    <!-- Update price of product-->
                    {% if product.special_price is not None %}
                    <b>Price : </b><del style="color:rgb(255, 90, 90)">{{ product.price | floatformat:'g' }}
                        Bath</del>{{ product.special_price | floatformat:'g' }} Bath<br>
                    {% else %}
                    {% if product.price is not None %}
                    <b>Price : </b>{{ product.price | floatformat:'g' }} Bath<br>
                    {% else %}
                    <br>
                    {% endif %}
                    {% endif %}
                    <!-- Check promotion end of product -->
                    {% if product.promotion_end is not None %}
                    <b>Promotion End : </b>{{ product.promotion_end | date:'j N Y' }}<br>
                    {% else %}
                    <br>
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <!-- Check status of product -->
                    <div class="btn-group">
                        {% if product.quantity == 0 %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Sold out</button>
                        {% else %}
                        {% if product.quantity is not None %}
                        <a type="button" class="btn btn-sm btn-primary fw-bold"
                            href="{% url 'app_general:add_to_cart-page' slug=product.slug %}">Add to Cart</a>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Empty</button>
                        {% endif %}
                        {% endif %}
                        <a class="btn btn-sm btn-link" href="{% url 'app_product:product-page' product.product_code %}">
                            Learn more
                        </a>
                    </div>
                    <!-- Update date for edit -->
                    <small class="text-muted">{{ product.updated | date:'j N Y' }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

app_product/templates/app_product/tea.html
{% extends 'app_general/base.html' %}

{% load static %}

{% block title %}
<title>Products | Tea</title>
{% endblock %}

{% block content %}
<div class="container text-white" align="center">
    <h1>Tea</h1>
</div>
{% if check_product == 0 %}
<div class="container mt-3 text-muted text-center">
    <h3>Don't have product.</h3>
</div>
{% else %}
<div class="container mt-3 row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    {% for product in tea %}
    <!-- Product detail -->
    <div class="col">
        <div class="card shadow-sm mb-1">
            {% if product.photo %}
            <img class="card-img-top" src="{{ product.photo.url }}" alt="Card image" style="width:100%">
            {% endif %}
            <small class="text-muted text-end p-1">{{ product.product_code }}</small>
            <div class="card-body">
                <a class="card-title fw-bold text-white btn btn-success position-relative"
                    href="{% url 'app_product:product-page' product.product_code %}">
                    {{ product.title }}
                    {% if product.is_premium %}
                    <span
                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-black">
                        Premium !
                    </span>
                    {% endif %}
                </a>
                <p class="card-text">
                    <b> :: {{ product.type }} :: </b><br>
                    <!-- Check quantity of product -->
                    {% if product.quantity is not None %}
                    <b>Quantity : </b>{{ product.quantity }}<br>
                    {% else %}
                    <b class="text-danger">There are no order yet!</b><br>
                    {% endif %}
                    <!-- Update price of product -->
                    {% if product.special_price is not None %}
                    <b>Price : </b><del style="color:rgb(255, 90, 90)">{{ product.price | floatformat:'g' }}
                        Bath</del>&nbsp&nbsp{{ product.special_price | floatformat:'g' }} Bath<br>
                    {% else %}
                    {% if product.price is not None %}
                    <b>Price : </b>{{ product.price | floatformat:'g' }} Bath<br>
                    {% else %}
                    <br>
                    {% endif %}
                    {% endif %}
                    <!-- Check promotion end of product -->
                    {% if product.promotion_end is not None %}
                    <b>Promotion End : </b>{{ product.promotion_end | date:'j N Y' }}<br>
                    {% else %}
                    <br>
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <!-- Update status of product -->
                        {% if product.quantity == 0 %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Sold out</button>
                        {% else %}
                        {% if product.quantity is not None %}
                        <a type="button" class="btn btn-sm btn-primary fw-bold"
                            href="{% url 'app_general:add_to_cart-page' slug=product.slug %}">Add to Cart</a>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-danger fw-bold">Empty</button>
                        {% endif %}
                        {% endif %}
                        <a class="btn btn-sm btn-link"
                            href="{% url 'app_product:product-page' product.product_code %}">Learn more</a>
                    </div>
                    <small class="text-muted">{{ product.updated | date:'j N Y' }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}