Project_NAT/urls.py
from django.contrib import admin
from django.urls import path, include
# import login function
from django.contrib.auth import views as auth_views
# import fuction upload photo
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('app_product.urls', 'app_product'), namespace = 'app_product')),
    path('', include(('app_general.urls', 'app_general'), namespace = 'app_general')),
    # Mapping login and logout
    path('login/', auth_views.LoginView.as_view(template_name='app_general/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='app_general/logout.html'), name='logout'),
]

# Path upload photo
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_general/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.Home, name='home-page'),
    path('about_user/', views.AboutUser, name='about_user-page'),
    path('register_user/', views.RegisterUser, name='register_user-page'),
    path('contact/',views.ContactMessage, name='contact-page'),
    re_path(r'^add_to_cart/(?P<slug>[\w-]+)/$', views.add_to_cart, name='add_to_cart-page'),
    path('cart/', views.cart_list, name='cart_list-page'),
	re_path(r'^delete_cart/(?P<slug>[\w-]+)/$', views.cart_delete, name='delete_product-page'),
	path('order/', views.order, name='order-page'),
    path('add_customers/', views.Add_Customer, name='add-customer-page'),
    path('order/del_customers/<customer_id>', views.Delete_Customer, name='del_customer-page'),
	path('order/<customer_id>/', views.Select_Customer, name='select_customer-page'),
    path('thank_you/', views.Thankyou, name='thank_you-page'),
    path('history_shopping/', views.history_shopping, name='history_shop-page')
]

app_product/urls.py
from django.urls import path
from app_product import views

urlpatterns = [
	path('', views.All_Products, name='products-page' ),
	path('<product_code>', views.One_Product, name='product-page'),
	path('coffee/', views.All_Coffee, name='products_coffee-page'),
	path('tea/', views.All_Tea, name='products_tea-page'),
	path('milk/', views.All_Milk, name='products_milk-page'),
	path('cake/', views.All_Cake, name='products_cake-page'),
]

app_general/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Contact(models.Model):
    contact_id = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    title = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    description = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{} : {}'.format(self.title, self.email)

class Customer(models.Model):
    customer_id = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    first_name = models.CharField(max_length = 225)
    last_name = models.CharField(max_length = 225)
    country = models.CharField(max_length = 225)
    city = models.CharField(max_length = 225)
    address = models.CharField(max_length = 225)
    phone = models.CharField(max_length = 225)
    def __str__(self) -> str:
    	return f'{self.first_name} {self.last_name}'

class Delivery(models.Model):
    STATUS = [
        ('Disapproved', 'Disapproved'), 
        ('Approve', 'Approve'), 
        ('Banned', 'Banned')
    ]
    PAYMENT = [
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Bank Transfer', 'Bank Transfer')
    ]
    delivery_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey('app_general.Customer', on_delete = models.CASCADE, null = True)
    status = models.CharField(max_length = 50, choices = STATUS, default = 'Disapproved')
    note = models.CharField(max_length = 100, null = True)
    payment_method = models.CharField(max_length = 50, choices = PAYMENT, default = 'Cash On Delivery')
    delivery_date = models.DateTimeField(auto_now_add = True)

class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    delivery = models.ForeignKey('app_general.Delivery', on_delete = models.CASCADE, null = True)
    product = models.ForeignKey('app_product.Product',  on_delete = models.CASCADE, null = True)
    quantity = models.IntegerField()
    unit_price = models.IntegerField()
    total_price = models.IntegerField()
    order_date = models.DateTimeField(auto_now_add = True)

app_general/forms.py
from django import forms
from app_product.models import *
from app_general.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ContactForm(forms.ModelForm):
	title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	description = forms.CharField(max_length=255, widget=forms.Textarea(attrs={'class':'form-control'}))
	class Meta:
		model = Contact
		fields = ('title','email','description')

class RegisterUserForm(UserCreationForm):
	first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	class Meta:
		model = User
		fields = ('username','first_name','last_name','email','password1','password2')
	def __init__(self, *args, **kwargs):
		super(RegisterUserForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['class'] = 'form-control'

class CustomerForm(forms.ModelForm):
	# Adjust from delivery
	first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(label='Last Name', widget=forms.TextInput(attrs={'class':'form-control'}))
	country = forms.CharField(label="Country", widget=forms.TextInput(attrs={'class':'form-control'}))
	city = forms.CharField(label="City", widget=forms.TextInput(attrs={'class':'form-control'}))
	address = forms.CharField(label="Address", widget=forms.TextInput(attrs={'class':'form-control'}))
	phone = forms.CharField(label="Phone Number", widget=forms.TextInput(attrs={'class':'form-control'}))
	class Meta:
		model = Customer
		fields = ('first_name','last_name','country','city','address','phone')

class OrderForm(forms.ModelForm):
	PAYMENT = [
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Bank Transfer', 'Bank Transfer')
	]
	payment_method = forms.ChoiceField(label="Payment Method", required = True, choices = PAYMENT, widget=forms.RadioSelect)	
	note = forms.CharField(label="Message", initial="No Comment", widget=forms.TextInput(attrs={'class':'form-control'}))
	class Meta:
		model = Delivery
		fields = ('payment_method','note')

app_general/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from app_general.forms import *
from django.contrib.auth import authenticate, login
from django.contrib import messages
from app_product.models import Product
from django.contrib.auth.models import User

# Create your views here.

# Home-Page
def Home(request):
	return render(request, 'app_general/home.html')

# AboutMe-Page (login requirement)
@login_required
def AboutUser(request):
	return render(request, 'app_general/about.html')

# Register-Page (After register auto login)
def RegisterUser(request):
	if request.method == "POST":
		form = RegisterUserForm(request.POST)
		if form.is_valid():
			form.save()
			data_username = form.cleaned_data['username']
			data_password = form.cleaned_data['password1']
			user = authenticate(username=data_username, password=data_password)
			login(request, user)
			messages.success(request, ("Registration Successful"))
			return redirect('app_general:home-page')
	else:
		form = RegisterUserForm()
	context = { 'form' : form }
	return render(request, 'app_general/register.html', context)

# Contact-Page
def ContactMessage(request):
	if request.method == "POST":
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('app_general:home-page')
	else:
		form = ContactForm()
	context = { 'form' : form }
	return render(request, 'app_general/contact.html', context)

# Add Product Function in Cart
# Note Variable
# Price 1. price >> normal price | 2. special_price >> special price  | 3. product_price >> real price | 4. total_price >> summation price of product in cart
# Quantities 1. quantity >> quantity of product in database | 2. qty >> quantities of product in cart
@login_required
def add_to_cart(request, slug):
	product = get_object_or_404(Product, slug = slug)
	cart_items = request.session.get('cart_items') or []
	item_in_cart = False
	if product.quantity >= 1:
		# Update item in cart ( Have this item in cart )
		for item in cart_items:
			if item.get('slug') == product.slug:
				# Update product price
				if item.get('special_price') is not None:
					item['product_price'] = int(item.get('special_price'))
				# Update product quantities
				if product.quantity > item['qty']:
					item['qty'] = int(item.get('qty')) + 1
					item['total_price'] = int(item.get('qty')) * int(item.get('product_price'))
				item_in_cart = True
		# Add new item in cart
		if not item_in_cart:
			# Update product price
			if product.special_price is not None:
				product_price = product.special_price
			else:
				product_price = product.price
			cart_items.append({
				'product_id' : product.product_id,
				'product_code' : product.product_code,
				'slug' : product.slug,
				'title' : product.title,
				'price' : product.price,
				'product_price' : product_price,
				'qty' : 1,
				'total_price' : product_price,
			})
		request.session['cart_items'] = cart_items
	# Connect to cart_list function
	return HttpResponseRedirect(reverse('app_general:cart_list-page'))

# Delete Product Function in Cart
def cart_delete(request, slug):
	cart_items = request.session.get('cart_items') or []
	for i in range(len(cart_items)):
		if cart_items[i]['slug'] == slug:
			del cart_items[i]
			break
	request.session['cart_items'] = cart_items
	# Connect to cart_list function
	return HttpResponseRedirect(reverse('app_general:cart_list-page', kwargs={}))

# Cart-Page
@login_required
def cart_list(request):
	cart_items = request.session.get('cart_items') or []
	total_qty = 0
	total_price = 0
	add_shipping_cost = False
	# Update total quantity and total price of product
	for item in cart_items:
		total_price += item.get('total_price')
		total_qty += item.get('qty')
	request.session['total_qty'] = total_qty
	request.session['total_price'] = total_price
	request.session['add_shipping_cost'] = add_shipping_cost
	if request.method == "POST":
		# Connect to order function
		return HttpResponseRedirect(reverse('app_general:order-page', kwargs={}))
	return render(request, 'app_general/cart.html', {'cart_items' : cart_items,})

# Register Customer Function and save to Database
@login_required
def Add_Customer(request):
	customer = []
	if request.method == "POST":
		form = CustomerForm(request.POST)
		if form.is_valid():
			customer.append({
				'first_name' : form.cleaned_data['first_name'],
				'last_name' : form.cleaned_data['last_name'],
				'country' : form.cleaned_data['country'],
				'city' : form.cleaned_data['city'],
				'address' : form.cleaned_data['address'],
				'phone' : form.cleaned_data['phone']
			})
		# Add new customer to database
		username = request.user.username
		new_customer = Customer()
		new_customer.user = User.objects.get(username=username)
		new_customer.first_name = customer[0]['first_name']
		new_customer.last_name = customer[0]['last_name']
		new_customer.country = customer[0]['country']
		new_customer.city = customer[0]['city']
		new_customer.address = customer[0]['address']
		new_customer.phone = customer[0]['phone']
		new_customer.save()
		request.session['customer'] = customer
		request.session['customer_id'] = new_customer.customer_id
		# Connect to order function
		return HttpResponseRedirect(reverse('app_general:order-page'))
	else:
		form = CustomerForm()
	return render(request, 'app_general/add_customer.html', {
		'form':form,
		})

# Select Customer Function in Database
def Select_Customer(request, customer_id):
	customers = Customer.objects.get(customer_id = customer_id)
	customer = []
	customer.append({
		'first_name' : customers.first_name,
		'last_name' : customers.last_name,
		'country' : customers.country,
		'city' : customers.city,
		'address' : customers.address,
		'phone' : customers.phone
	})
	request.session['customer'] = customer
	request.session['customer_id'] = customers.customer_id
	# Connect to order function
	return HttpResponseRedirect(reverse('app_general:order-page', kwargs={}))

# Delete customer Function in Database
def Delete_Customer(request, customer_id):
	del_customer = Customer.objects.get(customer_id = customer_id)
	del_customer.delete()
	request.session['customer'] = []
	# Connect to order function
	return HttpResponseRedirect(reverse('app_general:order-page', kwargs={}))

# order Function
@login_required
def order(request):
	cart_items = request.session.get('cart_items') or []
	customer = request.session.get('customer') or []
	customer_id = request.session.get('customer_id') or []
	total_price = request.session.get('total_price') or []
	add_shipping_cost = request.session.get('add_shipping_cost')
	all_customer = Customer.objects.all()
	shipping_cost = 40
	try:
		my_order = True
		# update total price (+ shipping cost)
		if not add_shipping_cost:
			total_price += shipping_cost
			add_shipping_cost = True
			request.session['total_price'] = total_price
			request.session['add_shipping_cost'] = add_shipping_cost
		if request.method == "POST":
			# Part delivery (+ data for note and payment_method)
			delivery = []
			form = OrderForm(request.POST)
			if form.is_valid():
				delivery.append({
					'note' : form.cleaned_data['note'],
					'payment_method' : form.cleaned_data['payment_method']
				})
				request.session['delivery'] = delivery
			# Save Delivery to database
			new_delivery = Delivery()
			try:
				new_delivery.customer = Customer.objects.get(customer_id = customer_id)
				new_delivery.note = delivery[0]['note']
				new_delivery.payment_method = delivery[0]['payment_method']
				new_delivery.save()
			except:
				return HttpResponseRedirect(reverse('app_general:order-page'))
			# Save new order in database
			for data in range(len(cart_items)):
				new_order = Order()
				new_order.delivery = Delivery.objects.all().last()
				new_order.product = Product.objects.get(product_id = cart_items[data]['product_id'])
				new_order.quantity = cart_items[data]['qty']
				new_order.unit_price = cart_items[data]['product_price']
				new_order.total_price = cart_items[data]['total_price']
				new_order.save()
				# Update quantity of product in database
				update_quantity = get_object_or_404(Product, product_code = cart_items[data]['product_code'])
				update_quantity.quantity -= new_order.quantity
				update_quantity.save()
			request.session['total_qty']  = []
			request.session['cart_items']  = []
			request.session['total_price'] = []
			# Connect to Thankyou function
			return HttpResponseRedirect(reverse('app_general:thank_you-page'))
		else:
			form = OrderForm()
	except:
		my_order = False
		form = OrderForm()
	context = {
		'form' : form,
		'all_customer' : all_customer,
		'cart_items' : cart_items,
		'customer' : customer,
		'shipping_cost' : shipping_cost,
		'my_order' : my_order
	}
	return render(request, 'app_general/order.html', context)

# ThankYou-Page (After Checkout in Order-Page)
@login_required
def Thankyou(request):
	return render(request, 'app_general/thank_for_shopping.html')

# History Shopping
@login_required
def history_shopping(request):
	account = request.user.username
	username = User.objects.get(username=account)
	customers = Customer.objects.filter(user=username)
	history_shop = []
	# Filter data
	for customer in customers:
		deliveries = Delivery.objects.filter(customer_id = customer)
		for delivery in deliveries:
			orders = Order.objects.filter(delivery = delivery.delivery_id)
			for order in orders:
				products = Product.objects.filter(product_id = order.product_id)
				for product in products:
					history_shop.append({
						'delivery' : delivery.delivery_id,
						'date' : delivery.delivery_date.strftime('%Y/%m/%d'),
						'customer' : customer,
						'product' : product.title,
						'quantities' : order.quantity,
						'total_price' : order.total_price
					})
	status = len(history_shop)
	context = {
		'history_shop' : history_shop,
		'status' : status
	}

app_general/templates/app_general/cart.html
{% extends 'app_general/base.html' %}
{% load static %}

{% block title %}
<title>Cart ( {{ request.session.total_qty }} ) | Project_NAT</title>
{% endblock %}


{% block content %}
<div class="text-white" align="center">
    <h1>Cart List</h1>
</div>

<form action="{% url 'app_general:cart_list-page' %}" class="container mt-3" method="POST">
    {% csrf_token %}
    {% if not cart_items %}
    <h3 class="text-center text-muted">Oops! Your cart is empty!</h3>
    <div class="mb-4 text-center text-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="75" height="75" fill="currentColor"
            class="bi bi-emoji-frown-fill" viewBox="0 0 16 16">
            <path
                d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm-2.715 5.933a.5.5 0 0 1-.183-.683A4.498 4.498 0 0 1 8 9.5a4.5 4.5 0 0 1 3.898 2.25.5.5 0 0 1-.866.5A3.498 3.498 0 0 0 8 10.5a3.498 3.498 0 0 0-3.032 1.75.5.5 0 0 1-.683.183zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z" />
        </svg>
    </div>
    {% else %}
    <div class="table-responsive-sm">
        <table class="table table-dark table-hover">
            <thead>
                <tr class="text-nowrap" align="center">
                    <th>Product</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <!-- Show all order in cart -->
                {% for product in cart_items %}
                <tr class="text-nowrap" align="center">
                    <td>
                        <a class="btn btn-success" href="{% url 'app_product:product-page' product.product_code %}">
                            {{ product.title }}
                        </a>
                    </td>
                    <td>฿ {{ product.product_price | floatformat:'g' }}</td>
                    <td>{{ product.qty }}</td>
                    <td>฿ {{ product.total_price | floatformat:'g' }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'app_general:delete_product-page' slug=product.slug %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-trash-fill" viewBox="0 0 16 16">
                                <path
                                    d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                            </svg>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            <tbody class="fw-bold">
                <tr class="text-nowrap" align="center">
                    <td>
                        <h5>Total</h5>
                    </td>
                    <td></td>
                    <td>
                        <h5>{{ request.session.total_qty }}</h5>
                    </td>
                    <td>
                        <h5>฿ {{ request.session.total_price | floatformat:'g' }}</h5>
                    </td>
                    <td><button class="btn btn-primary" type="submit">Check Out</button></td>
                </tr>
            </tbody>
            </tbody>
        </table>
    </div>
    {% endif %}
</form>
{% endblock %}

app_general/templates/app_general/contact.html
{% extends 'app_general/base.html' %}

{% block title %}
<title>Contact | Project_NAT</title>
{% endblock title %}

{% block content %}
<div class="container text-white" align="center">
    <h1>Contact</h1>
    {% if form.errors %}
    <div class="alert alert-warning">
        <strong>Warning!</strong> This alert box could indicate a warning that might need attention.
    </div>
    {% endif %}
</div>
<form class="text-white container mt-3" action="{% url 'app_general:contact-page' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-field">
        <button class="btn btn-primary" type="submit">Send Message</button>
    </div>
</form>
{% endblock %}

app_general/templates/app_general/order.html
{% extends 'app_general/base.html' %}
{% load static %}

{% block title %}
<title>Order | Project_NAT</title>
{% endblock %}

{% block content %}
<div class="row bg-black" align="center">
    <div class="col-2">
        <a class="btn btn-black" href="{% url 'app_general:cart_list-page' %}">
            <svg style="color:rgb(130, 130, 130)" xmlns="http://www.w3.org/2000/svg" width="30" height="30"
                fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
        </a>
    </div>
    <div class="col-8 text-white">
        <h1>Order List</h1>
    </div>
</div>
<form class="text-white container mt-3" action="{% url 'app_general:order-page' %}" method="POST">
    {% csrf_token %}
    <div class="text-muted">
        {% if my_order %}
        <div class="text-white" align="left">
            <h3 class="text-muted">Delivery Address</h3>
            <!-- Add Customer Function -->
            <a class="btn btn-secondary text-black fw-bold rounded-pill"
                href="{% url 'app_general:add-customer-page' %}">+ Add Address</a> &nbsp;
            <!-- Select Customer Function-->
            <button class="btn btn-secondary text-black fw-bold rounded-pill" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Select Your
                Address</button>
            <p>
            <div class="collapse" id="collapseExample">
                <div class="card-secondry card-body">
                    {% for customer in all_customer %}
                    <div class="card">
                        <div class="card-header row text-black fw-bold">
                            <h5 class="col-8">
                                {{ customer.first_name }} {{ customer.last_name }}
                            </h5>
                            <div class="btn-group col-4">
                                <a type="button" class="btn btn-sm btn-primary text-white"
                                    href="{% url 'app_general:select_customer-page' customer_id=customer.customer_id%}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                                        <path
                                            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
                                    </svg>
                                </a>
                                <a type="button" type="submit" class="btn btn-sm btn-danger text-white"
                                    href="{% url 'app_general:del_customer-page' customer_id=customer.customer_id%}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-trash-fill" viewBox="0 0 16 16">
                                        <path
                                            d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                                    </svg>
                                </a>
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><b>Address : </b>{{ customer.country }}, {{ customer.city }}, {{ customer.address }}</li>
                            <li class="list-group-item"><b>Tel : </b>{{ customer.phone }}</li>
                        </ul>
                    </div><br>
                    {% endfor %}
                </div>
            </div>
            </p>
            <!-- Show Customer -->
            {% for data in customer %}
            <p>
            <div class="card">
                <div class="card-header text-black fw-bold row">
                    <div class="col-8">
                        Name : {{ data.first_name }} {{ data.last_name }}
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <b>Country : </b>{{ data.country }}<br>
                        <b>City : </b>{{ data.city }}<br>
                        <b>Address : </b>{{ data.address }}<br>
                    </li>
                    <li class="list-group-item">
                        <b>Tel : </b>{{ data.phone }}
                    </li>
                    <li class="list-group-item">
                        {{ form.as_p }}
                    </li>
                </ul>
            </div>
            </p>
            {% endfor %}
        </div>
        <!-- Show order from order-page -->
        <div class="table-responsive-sm">
            <table class="table table-dark">
                <h3>Order List</h3>
                <thead>
                    <tr class="text-nowrap" align="center">
                        <th>Product</th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in cart_items %}
                    <tr class="text-nowrap" align="center">
                        <td>{{ product.title }}</td>
                        <td>฿ {{ product.product_price | floatformat:'g' }}</td>
                        <td>{{ product.qty }}</td>
                        <td>฿ {{ product.total_price | floatformat:'g' }}</td>
                    </tr>
                    {% endfor %}
                <tbody class="fw-bold">
                    <tr class="text-nowrap" align="center">
                        <td colspan="2" align="right">Shipping Cost</td>
                        <td></td>
                        <td>฿ {{ shipping_cost | floatformat:'g' }}</td>
                    </tr>
                </tbody>
                <tbody class="fw-bold">
                    <tr class="text-nowrap" style="color:rgb(250, 200, 75)" align="center">
                        <td colspan="2" align="right">
                            <h5>Total</h5>
                        </td>
                        <td>
                            <h5>{{ request.session.total_qty }}</h5>
                        </td>
                        <td>
                            <h5>฿ {{ request.session.total_price | floatformat:'g' }}</h5>
                        </td>
                    </tr>
                </tbody>
                </tbody>
            </table>
            <div class="form-field text-end">
                <button class="btn btn-primary" type="submit">Place Order</button>
            </div>
        </div>
        {% else %}
        <h3 class="text-center">Your haven't placed any order yet.</h3>
        {% endif %}
    </div>
</form>
{% endblock %}